# Experimental design

The first step of planning an RNAseq experiment is asking yourself whether RNAseq will answer the intended research question and whether you need to do it. Sequencing experiments are not cheap and you can save yourself a lot of time and money by ensuring that the sequencing that you are doing is suited to answering the research question at hand.

Consider: if your intent is to study the expression of a small number of genes, RT-PCR might be more appropriate and cheaper for your needs. If you intend to study the changes in expression accross all genes in your organism of interest, then RNAseq is suitable for the experiment. Then - what type of RNAseq - there are many different protocols that can be performed.

If your intent is to study changes in gene expression in individual cells, then you would use a single cell sequencing approach. If however, you do not care for the fine detail of individual cells, then you might consider using a bulk sequencing protocol.



are you interested in changes in gene expression levels or do you want to study structural variations within genes? Short read sequencing 


The most common application of RNAseq that we see is to examine the changes in gene expression level between different experimental conditions. This workshop has been designed with this understanding that this is the type of analysis that you intend to perform.

Is RNAseq what you need? Should I do it? and is going to answer my questions? Do I have the prerequisites?

Fundamentals of research -> Factor , Confounding factor, Variable to measure, Controls, Batch, Techinical replicates and not biological, Pooling samples, 


## Sequencing methods

Sequencing Decision. Transcriptomics for Bulk RNAseq. Short reads. Coverage.


## Batches and replicates (technical/biological)


Batch, Techinical replicates and not biological, Pooling samples, Randomization, Noise. Clonal (cell-lines, bacteria, inbred animalls) or not clonal organisms, Does my tissue has different cell types -> Cell sorting or single cell

